# Generated by Django 5.2.6 on 2025-10-01 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="course",
            options={"verbose_name": "Course", "verbose_name_plural": "Courses"},
        ),
        migrations.AlterModelOptions(
            name="examresult",
            options={
                "verbose_name": "Exam Result",
                "verbose_name_plural": "Exam Results",
            },
        ),
        migrations.AlterModelOptions(
            name="school",
            options={"verbose_name": "School", "verbose_name_plural": "Schools"},
        ),
        migrations.AlterModelOptions(
            name="student",
            options={"verbose_name": "Student", "verbose_name_plural": "Students"},
        ),
        migrations.AlterModelOptions(
            name="teacher",
            options={"verbose_name": "Teacher", "verbose_name_plural": "Teachers"},
        ),
        migrations.AlterModelTable(
            name="course",
            table="course",
        ),
        migrations.AlterModelTable(
            name="examresult",
            table="exam_result",
        ),
        migrations.AlterModelTable(
            name="school",
            table="school",
        ),
        migrations.AlterModelTable(
            name="student",
            table="student",
        ),
        migrations.AlterModelTable(
            name="teacher",
            table="teacher",
        ),
    ]
