# Generated by Django 5.2.6 on 2025-10-07 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=55)),
                ("age", models.IntegerField()),
                ("department", models.CharField(max_length=55)),
                ("salary", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                "verbose_name": "Employee",
                "verbose_name_plural": "Employees",
                "db_table": "employee",
            },
        ),
    ]
